### ISSUE TITLE
Value in column X is not of type Boolean but is class java.lang.Boolean

### ISSUE THREAD

**Issue by dmarkhas** [Anchormen/sql4es#19] opened 2016-09-08 13:17 UTC
Hi there,

I'm running into an odd issue trying to run a simple select * from <type> statement, where type is a type that exists in more than one index (but the query, and the URL, are specifying a single index).

This is the query:

SELECT * from "data-generator-poc-async".arm

And this is the URL:
jdbc:sql4es://myelastichost:9302/data-generator-poc-async?cluster.name=test23

Using the exact same connection URL and query, I get the following results:

- Squirrel - returns all documents in the specified index, but with hundreds of columns that do not exist in the index at all (they do exist however for the arm type in other indices on the cluster). The values for all of these columns are being shown as NULL / false for boolean values.

- WorkbenchJ - Getting back an error: "Value in column '552' is not a Date but is String"
There are two problems here:
1) My index doesn't have 552 columns.. the count is probably skewed because it pulls in columns for the arm type from other indices
2) Using Squirrel I can see that the getColumnTypeName and getColumnClassName for column 552 are both java.sql.Date

- Apache Drill (ultimately this is what I want to use the sql4es driver with) - Getting back an error: "Value in column '783' is not of type boolean but is class java.lang.Boolean"

The data I have in the index is very simple, Am I doing something wrong? :)

**Comment by corneversloot** [comment] 2016-09-09 10:33
Thanks for the clear description! It sounds like a bug in which the metadata of the types in different indexes are being mixed. I will look into it. It might take some time though since im on vacation atm.

It would be cool if the driver can be used from within drill. It is on my list of things to try but did not yet find the time for it. Let me know how it works out.

**Comment by dmarkhas** [comment] 2016-09-09 17:01
It actually works relatively well in Drill :-)
Using a different index/type where there are only String/Long types, I can successfully query it with Drill and even join it with SQL Server (which is the end result I'm looking for).

However, I am only beginning experimenting with it. So far I've ran into a couple of issues:

- This topic, which is the most significant issue as it is completely breaks the ability to query certain indices
- Running SHOW DATABASES on Drill returns a list of all available indices in the ES cluster (excellent!), but only the index that was specified in the driver URL can actually be queried, whereas other indices return 0 rows. To query the other indices I have to change the URL..

**Comment by corneversloot** [comment] 2016-09-10 06:40
Well, you can switch to another index by executing the 'USE indexname' statement. There is no need to rebuild the connection using another url

**Comment by dmarkhas** [comment] 2016-09-10 07:25
Yes, I know, and it works well in Squirrel/WorkbenchJ, but not in Drill for some reason.. I need to give it some more time to find the pattern though.

--Dan

**Comment by corneversloot** [comment] 2016-09-10 07:32
The USE statement is purely a hint for the driver to make another index the 'active' one. Since drill is a distributed engine i wonder if the statement is applied to all the drillbits (driver instances). I guess it had something to do with this but im not sure.

**Comment by corneversloot** [comment] 2016-09-11 10:33
I have implemented a fix for this issue which has been build into the 0.8.2.3 jar file. I tested it briefly using SQLWorkbench (two indexes, each containing the same type with different fields) and queries only show the right fields. However, I was not able to test it extensively so it would be great if you can verify if it works in your setup as well.

As a side note; there is a way to query other indexes without executing the USE statement. In that scenario you will have to create an Alias encapsulating all the indexes you want to query and point the driver to that alias. This will enable you to query all the types within those indexes. However, if you do this you have to make sure that you do not have types with the same name but different fields within these indexes as you have now because the driver will not be able to keep those types apart (same issue you have now). Types which have the same name and the same fields are OK though.
I hope this makes sence... you can also read the [Index Alias documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html) from Elastic

**Comment by dmarkhas** [comment] 2016-09-11 10:44
Wow, thanks for the super fast response! :-)

I just tested it, and it no longer pulls all of the columns from the other indices, but I am still running into the issue in the topic: 

Caused by: java.sql.SQLException: Value in column '44' is not of type boolean but is class java.lang.Boolean
	at nl.anchormen.sql4es.ESResultSet.getBoolean(ESResultSet.java:242) ~[sql4es-0.8.2.3.jar:na]

I looked at your code (before your latest change) and printed out the exception that was being thrown, and this is it:

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String

It looks like it is coming from this line:

case Types.VARCHAR : return Boolean.parseBoolean((String)value);

Looks like (String)value is throwing this exception, but I'm not 100% sure...

**Comment by corneversloot** [comment] 2016-09-11 11:49
I implemented it as you suggest so that it works. I fear however that it is a workaround for another issue. Somehow the driver thinks the type of that specific field is VARCHAR instead of BOOLEAN which is the root cause of this problem which i will have to look into a bit.

**Comment by dmarkhas** [comment] 2016-09-11 12:51
Yes I believe you're right - I ran into the same issue with a different column where it failed on this line:
case Types.BIGINT : return ((Long)value).longValue() == 1 

with the following exception:
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Long

**Comment by dmarkhas** [comment] 2016-09-12 05:18
So I did a little more digging and I noticed that when running a query via Drill, the function ESDatabaseMetaData.getColumns is called with null,null,"arm",null (where arm is the type, aka the table name from Drill's perspective). This causes it to return all mappings for the type from all indices... 
I don't know if this call is being made from your code (I think not) or directly from Drill.

Is it possible to restrict it to use the default index if no index was provided? (maybe as a configuration option)

**Comment by corneversloot** [comment] 2016-09-12 06:20
I think it is performed by Drill and it is a bit sloppy they do it this way. It is relatively easy to make it configurable as you suggest and i will do that.

As a more general comment I always try to avoid types with the same name holding different kinds of data. This avoids some of the issues were are facing now and it will also make it easier to use elasticsearch aliases which to my opinion are very powerful :)

**Comment by dmarkhas** [comment] 2016-09-12 13:21
Yea, the issue with different types is not really a standard deployment – we don't have this kind of setup in production, only in the lab, where I encountered this issue :-)

--Dan

**Closed** 2016-10-08 11:38 UTC

**Comment by sudhirkumar1980** [comment] 2017-06-07 16:09
am able to connect to ES 5.4 using JDBC connection. But getting following error while using table input.

Field in question is of type long in ES. Do i have to use any any type conversion in sql query ?

2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Unexpected error
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : org.pentaho.di.core.exception.KettleDatabaseException:
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Couldn't get row from result set
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX -
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Unable to get value 'BigNumber(16)' from database resultset, index 0
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Value in column '1' is not of type BigDecimal but is class java.lang.Integer
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX -
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX -
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - at org.pentaho.di.core.database.Database.getRow(Database.java:2546)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - at org.pentaho.di.core.database.Database.getRow(Database.java:2516)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - at org.pentaho.di.core.database.Database.getRow(Database.java:2494)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - at org.pentaho.di.trans.steps.tableinput.TableInput.doQuery(TableInput.java:259)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - at org.pentaho.di.trans.steps.tableinput.TableInput.processRow(TableInput.java:140)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - at java.lang.Thread.run(Thread.java:745)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Caused by: org.pentaho.di.core.exception.KettleDatabaseException:
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Unable to get value 'BigNumber(16)' from database resultset, index 0
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Value in column '1' is not of type BigDecimal but is class java.lang.Integer
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX -
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - at org.pentaho.di.core.row.value.ValueMetaBase.getValueFromResultSet(ValueMetaBase.java:4964)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - at org.pentaho.di.core.database.BaseDatabaseMeta.getValueFromResultSet(BaseDatabaseMeta.java:2107)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - at org.pentaho.di.core.database.DatabaseMeta.getValueFromResultSet(DatabaseMeta.java:2950)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - at org.pentaho.di.core.database.Database.getRow(Database.java:2538)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - ... 6 more
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Caused by: java.sql.SQLException: Value in column '1' is not of type BigDecimal but is class java.lang.Integer
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - at nl.anchormen.sql4es.ESResultSet.getBigDecimal(ESResultSet.java:548)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - at org.pentaho.di.core.row.value.ValueMetaBase.getValueFromResultSet(ValueMetaBase.java:4919)
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - ... 9 more
2017/06/07 10:31:04 - XXXXXXXXXXXXXXXXXXX - Finished reading query, closing connection.
