### ISSUE TITLE
Seems to be incompatible with ELK version "2.4.0"

### ISSUE THREAD

**Issue by gogosofta** [Anchormen/sql4es#21] opened 2016-09-15 10:47 UTC
The client socket is disconnected the moment it tries to talk with the server.

**Comment by corneversloot** [comment] 2016-09-15 11:34
Well the latest driver has been build for elasticsearch version 2.3.5 so i guess it is not yet compatible with version 2.4.0. I will have to build it for the latest version in order for it to work. Ill update an close this issue once it is done.

**Comment by corneversloot** [comment] 2016-09-15 12:10
Ok, i have updated the driver to es 2.4. Please download the latest release (0.8.2.4) and use that driver to connect with your cluster. Let me know if that works as intended.

**Comment by gogosofta** [comment] 2016-09-15 12:15
Great! It works now. Thank you so much!

**Closed** 2016-09-15 17:17 UTC
